/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "我爱看",
  "tagline": "aikan 在线云盘文档",
  "url": "http://docs.aikan.pro",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "./img/favicon.ico",
  "organizationName": "Flowesy-7z",
  "projectName": "AikanPro",
  "i18n": {
    "defaultLocale": "zh-Hans",
    "locales": [
      "zh-Hans"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "scripts": [
    {
      "src": "/script/script.js",
      "async": true
    }
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "D:\\Code\\docs\\sidebars.js",
          "routeBasePath": "/",
          "showLastUpdateTime": true,
          "showLastUpdateAuthor": true,
          "editUrl": "https://github.com/Flowesy-7z/docs"
        },
        "blog": false,
        "theme": {
          "customCss": "D:\\Code\\docs\\src\\css\\custom.css"
        },
        "sitemap": {
          "changefreq": "weekly",
          "priority": 0.5
        }
      }
    ]
  ],
  "plugins": [
    "docusaurus-tailwindcss-loader",
    "docusaurus-plugin-image-zoom"
  ],
  "themes": [
    "@docusaurus/theme-live-codeblock",
    [
      "D:\\Code\\docs\\node_modules\\@easyops-cn\\docusaurus-search-local\\dist\\server\\server\\index.js",
      {
        "hashed": true,
        "indexBlog": false,
        "language": [
          "en",
          "zh"
        ],
        "docsRouteBasePath": "/",
        "highlightSearchTermsOnTargetPage": true,
        "explicitSearchResultPath": true
      }
    ]
  ],
  "themeConfig": {
    "zoom": {
      "selector": ".markdown img",
      "background": {
        "light": "rgb(255, 255, 255)",
        "dark": "rgb(50, 50, 50)"
      },
      "config": {}
    },
    "docs": {
      "sidebar": {
        "hideable": true,
        "autoCollapseCategories": true
      },
      "versionPersistence": "localStorage"
    },
    "colorMode": {
      "disableSwitch": false,
      "respectPrefersColorScheme": true,
      "defaultMode": "light"
    },
    "navbar": {
      "title": "AikanPro",
      "logo": {
        "alt": "我爱看",
        "src": "./img/aikan.png"
      },
      "items": [
        {
          "href": "https://qxzhi.com",
          "label": "PC演示站",
          "position": "left"
        },
        {
          "label": "移动端演示站",
          "href": "https://m.qxzhi.com",
          "position": "left"
        },
        {
          "type": "dropdown",
          "label": "QQ 交流群",
          "items": [
            {
              "label": "QQ 交流群",
              "href": "http://yl.qxzhi.com/liuli"
            },
            {
              "label": "QQ 交流群",
              "href": "http://yl.qxzhi.com/liuli"
            }
          ],
          "position": "left"
        },
        {
          "label": "服务器推荐✨",
          "href": "/ad/",
          "position": "left"
        },
        {
          "label": "我要提 BUG",
          "href": "http://yl.qxzhi.com/liuli",
          "position": "left"
        },
        {
          "label": "技术支持",
          "href": "/support/",
          "position": "left"
        },
        {
          "href": "https://github.com/Flowesy-7z/docs",
          "position": "right",
          "className": "header-github-link"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "关于",
          "items": [
            {
              "label": "官网",
              "to": "https://cdn.li.qxzhi.com"
            },
            {
              "label": "Github (文档)",
              "to": "https://github.com/Flowesy-7z/docs"
            }
          ]
        },
        {
          "title": "社区",
          "items": [
            {
              "label": "QQ 群",
              "href": "http://yl.qxzhi.com/liuli"
            },
            {
              "label": "联系作者",
              "href": "http://yl.qxzhi.com/2926233597"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 AikanPro, Inc. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash",
        "properties"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        },
        {
          "className": "code-block-primary-line",
          "line": "highlight blue next"
        },
        {
          "className": "code-block-warning-line",
          "line": "highlight yellow next"
        }
      ]
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    },
    "liveCodeBlock": {
      "playgroundPosition": "bottom"
    }
  },
  "baseUrlIssueBanner": true,
  "future": {
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  }
};
